local converter = require('jtt.converter')

describe("JSON to TypeScript Converter", function()
  describe("is_json_buffer", function()
    it("detects json buffer by filetype", function()
      local result = converter.is_json_buffer('json')
      assert.is_true(result)
    end)

    it("returns false for non-json filetype", function()
      local result = converter.is_json_buffer('lua')
      assert.is_false(result)
    end)
  end)
end)